[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/.next/standalone"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
